[package]
name = "dhcp-ms-to-isc-dhcp"
version = "1.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
lazy_static = "1.5.0"
minijinja = "2.15.1"
quick-xml = { version = "0.39.0", features = ["serialize"] }
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
wasm-bindgen = "0.2.112"

[dev-dependencies]
rstest = "0.26.1"
